---
title: "App features"
output:
  html_document:
    theme: cosmo
editor_options: 
  markdown: 
    wrap: 72
---

```{=html}
<style type="text/css">
h1.title {
  font-size: 36px;
  font-weight: 500;
  color: DarkRed;
  text-align: center;
}
</style>
```
```{r echo=FALSE}
library(fontawesome)
```

<hr>

<center>

```{r echo = FALSE}
fa("notes-medical",  width = "3em", fill = "indianred", fill_opacity = 0.8)
```

**Effect size**\
Studying the treatment effect for the composite endpoint\
[Time to
event](https://www.grbio.eu/compare/CompARETimeToEvent/?tab=%22tab_effect%22)         [Binary](https://www.grbio.eu/compare/CompAREBinary/?tab=%22tab_effect%22)<br>

<center>

<br>

```{r echo = FALSE}
fa("users-line", width = "3em", fill = "indianred", fill_opacity = 0.8)
```

**Sample Size**\
Computing the number of patients under different scenarios\
[Time to
event](https://www.grbio.eu/compare/CompARETimeToEvent/?tab=%22tab_sample%22)         [Binary](https://www.grbio.eu/compare/CompAREBinary/?tab=%22tab_sample%22)<br>

<center>

<br>

```{r echo = FALSE}
fa("arrow-right-arrow-left", width = "3em", fill = "indianred", fill_opacity = 0.8)
```

**Endpoint Selection**\
Identifying the best endpoint combination for the design\
[Time to
event](https://www.grbio.eu/compare/CompARETimeToEvent/?tab=%22tab_endpoint%22)         [Binary](https://www.grbio.eu/compare/CompAREBinary/?tab=%22tab_endpoint%22)<br>

<center>

<br>

```{r echo = FALSE}
fa("arrows-rotate", width = "3em", fill = "indianred", fill_opacity = 0.8)
```

**Association**\
Assessing the degree of association between components\
[Binary](https://www.grbio.eu/compare/CompAREBinary/?tab=%22tab_correlation%22)<br>

<hr>
