---
title: "CompARE"
output: html_document
date: "2024-03-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Implementation guide for web traffic analytics metrics and shiny applications.

The goal of this report is define the steps to implement in the CompARE Github Page, traffic analytics metrics for both the CompARE website and the CompARE shiny apps.

Hemos creado una Github Page mostrando el proyecto CompARE, con información sobre el paquete desarrollado y las aplicaciones Shiny. 

Nuestro objetivo es mostrar el número de usuarios totales que visitan:

1.- La página web

2.- Las dos aplicaciones Shiny (Binary y Time to Event)

## Pasos

### Creación de una cuenta en Google Analytics
Creación de dos propiedades. Una para las Shiny Apps y otra para la Web. Se ha usado la cuenta del grbio para crear estas dos propiedades.
Hemos reciclado una propiedad existente para mostrar el trafico de datos de las Shiny Apps. Esta propiedad lleva registrando los datos de tráfico desde el 21 de febrero del 2019. Para la nueva web generada a partir de Github, hemos creado una nueva propiedad iniciando el seguimiento del tráfico de datos el dia 13 de febrero de 2024.

### Empezar a registrar el tráfico de visitas en cada una de las propiedades
Una vez definidas las dos propiedades tenemos que copiar la etiqueta de google al sitio web o aplicación shiny para que empiece a registrar los datos. 
En el caso de la web de Github copiaremos esta etiqueta en cada una de las páginas de la web.

Para las Shiny apps, se copiará en el fichero ui.R ?? (Revisar), Acceder a través del server.

Importante!, el flujo de datos puede tardar hasta 48 horas en activarse. 

### Crear un report para obtener los datos que nos interesan en la Google Sheets Report Extension.
Una vez hemos comprobado que tanto las Apps como la Web están siendo trackeadas podemos exportar los datos que vemos en la plataforma de Google Analytics, en una Google Sheet.
Primero de todo nos descargarmos la extensión de Google Sheets "GA4 Magic Reports". 
GA4 Magic Reports is a Google Sheets add-on that helps you to view and edit Google Analytics 4 data more easily in Google Sheets.
Una vez instalada, crearemos un nuevo informe para cada uno de las dos fuentes (Web y Shiny Apps) donde queremos obtener la información proporcionada por Google Analytics.
Configuraremos los parametros que deseamos importar así como las fechas de registro y los filtros necesarios. A continuación, programaremos la actualización de la descarga de los datos para que lo haga diariamente.
Finalmente, ejecutaremos el informe y ya podremos ver los primeros datos hasta el mismo dia. 
La idea es que cada dia estos datos se vayan actualizando con la información que importa de Google Analytics.



### Importar estos datos en nuestro proyecto de R
El siguiente paso será importar estos datos de la hoja de cálculo a nuestro repositorio/proyecto de R donde tenemos nuestra plana web y donde queremos mostrar estos números informativos.
Para ello tenemos que copiar el enlace del report de Google Sheet asegurandonos que el accesso al documento es para cualquier persona que internet que tenga el enlace. Por defecto, muchas organizaciones tiene está opción restringida con la posibilidad de compartir documentos únicamente entre miembros de la entidad. Así que esto hay que tenerlo presente por si se necesitan solicitar permisos.

Seleccionamos la página en la que queremos que se muestre toda la información.
Usaremos la libreria gsheets con la función gsheets2tbl para llamar la url donde esta el report de Goggle Sheets.
Una cosa a tener en cuenta es que siempre lee la primera primera hoja del documento. Así que una solución sería reordenar las hojas para que el report se encuentre como la primera hoja y la configuración de los parámetros en la segunda hoja. 

A continuación, simplemente hay que obtener la información  que nos interesan a través de la típica extracción de datos. 

Guardamos el número que nos interesa en un objeto R y lo podemos incluir en una "badge" para que quede más bonito.



### Automatizar el proceso para que estos datos se vayan actualizando diariamente
Github workflows. Documemnto YAML.
Tenemos que crear un documetno yaml con las instrucciones para que automatizo el proceso de actualización.
Cada dia renderiza el documento donde hemos añadido la info y actualiza la página web.

FIN

### TAREAS
#### Añadir pantallazos
#### Añadir código de ejemplo
#### Mejorar el texto
#### Traducir al inglés
#### Renderizar a HTML.





