---
title: "CompARE"
subtitle: "Welcome to CompARE - Designing feasible clinical trials"
output:
  html_document:
    theme: cosmo
editor_options: 
  markdown: 
    wrap: 72
---

```{=html}
<style type="text/css">
h1.title {
  display: none;
}
</style>
```
```{=html}
<style type="text/css">
.subtitle {
  font-size: 36px;
  font-weight: 500;
  color: DarkRed;
  text-align: center;
}
</style>
```
```{=html}
<style type="text/css">
  body{
  font-size: 12pt;
}
</style>
```
```{=html}
<head>
<title>CompARE</title>
</head>
```
<br>

```{r echo=FALSE}
# https://stackoverflow.com/questions/61313078/create-a-carousel-in-rmarkdown
objpath <- file.path(getwd(),"images/carousel_home")
slickR::slickR(
    list.files(objpath,full.names = TRUE,pattern = 'png'),
    height = 300,
    width = '95%')
```

<br>

<br>

### What is CompARE?

<hr>

**CompARE** is a web-platform inspired to provide help on issues
relating to trials with composite endpoints. **CompARE** may be used as
a tool for calculating the elements needed in the planning phase of
clinical trials involving composite endpoints. With its user-friendly
interface, CompARE allows to input the main parameters included in the
trial -such as the treatment effect on the components of the composite
endpoint, and its frequencies of occurrence- and helps provide power and
sample size calculations among others.

<br>

### Apps

<hr>

**CompARE** is split into two apps for time-to-event and binary
endpoints, respectively. They are implemented with the Shiny R package.
<br>

<ul class="pager">

<!--this is the style of the button-->

<li><a href="https://www.grbio.eu/compare/CompARETimeToEvent/">TIME-TO-EVENT
APP</a></li>

<li><a href="https://www.grbio.eu/compare/CompAREBinary/">BINARY
APP</a></li>

</ul>

<ul class="pager">

<!--this is the style of the button-->

<li><a href="https://www.grbio.eu/compare/CompARETimeToEvent/help_Tutorial.html">TIME-TO-EVENT
TUTORIAL</a></li>

<li><a href="https://www.grbio.eu/compare/CompAREBinary/Help-Tutorial.html">BINARY
TUTORIAL</a></li>

</ul>

<br>

### Features

<hr>

-   **Effect size**: Studying the treatment effect for the composite
    endpoint

-   **Sample Size**: Computing the number of patients under different
    scenarios

-   **Endpoint Selection**: Identifying the best endpoint combination
    for the design

-   **Association**: Assessing the degree of association between
    components

<br>

<hr>
