---
title: "Talks"
output:
  html_document:
    theme: cosmo
---

```{=html}
<style type="text/css">
h1.title {
  font-size: 36px;
  font-weight: 500;
  color: DarkRed;
  text-align: center;
}
</style>
```

<br>

1.  [G. Gómez, J. Cortés and M. Bofill (2019-07-15). CompARE: a web app to study Composite Endpoints. 40th Annual Conference of the International Society of Clinical Biostatistics (ISCB 2019, Leuven)](https://www.grbio.eu/compare/compareCover/files/2019ISCB_definitive.pdf)

2.  [J. Cortés and G. Gómez (2018-07-09). CompARE: Sample Size Calculation for Time-To-Event Composite Endpoints. XXIXth International Biometric Conference (IBC 2018)](https://2018.biometricconference.org/wp-content/uploads/2018/07/PROGRAMA-IBC-V11.pdf)

3.  [M. Bofill and G. Gómez (2018-07-09). Sample Size Derivation for Composite Binary Endpoints Accounting for Departures of the Anticipated Values. XXIXth International Biometric Conference (IBC 2018)](https://2018.biometricconference.org/wp-content/uploads/2018/07/PROGRAMA-IBC-V11.pdf)

4.  [M. Bofill and J.L. Jiménez (2018-01-19). Facing the challenges in clinical trials. III Jornadas Científicas de Estudiantes de la Sociedad Española de Biometría.](https://wp.bcamath.org/jjseb3/programa/)

5.  [J. Cortés, M. Bofill and G. Gómez (2018-01-19). Sample size calculation using CompARE. III Jornadas Científicas de Estudiantes de la Sociedad Española de Biometría.](https://wp.bcamath.org/jjseb3/programa/)

6.  [M. Bofill and G. Gómez (2017-09-07). Clinical trial designs with multiple binary endpoints. Congreso de Jóvenes Investigadores Real Sociedad Matemática Española.](https://rsmejovenes.blogs.uv.es/files/2017/01/actas_CJIRSME.pdf)

7.  [G. Gómez (2017-09-07). Non-proportional hazards: consequences on sample size. Conferencia Española de Biometría.](https://www.imus.us.es/CEB17/imagenes/ActasWebCEB2017.pdf)

8.  [M. Bofill and G. Gómez (2017-09). Clinical trial designs with multiple binary endpoints. Conferencia Española de Biometría.](https://www.imus.us.es/CEB17/imagenes/ActasWebCEB2017.pdf)

9.  [M. Bofill and G. Gómez (2017-07-10). Sample size derivation for binary composite endpoints. Annual Conference of the International Society of Clinical Biostatistics.](http://iscb2017.info/uploadedFiles/ISCB2017.y23bw/fileManager/ISCB2017%20Book%20of%20Abstracts.pdf)

10. [G. Gómez (2017-05-26). Sample size considerations for composite endpoints. Conference on Lifetime Data Science.](https://archive.stat.uconn.edu/lida17/program.pdf)

11. [M. Bofill and G. Gómez (2017-05). The anticipated odds ratios to decide the choice of a primary binary endpoint. Conference of the Eastern Mediterranean Region of the International Biometric Society.](https://docplayer.net/49550227-Book-of-abstracts-conference-of-the-eastern-mediterranean-region-and-the-italian-region-of-the-international-biometric-society.html)

12. [M. Bofill and G. Gómez (2017-01-20). Sample size determination using composite binary endpoints. Reunión general Biostatnet.](https://www.usc.es/biofarma/documentos/biostat.pdf)

13. [G. Gómez, M. Gómez and M. Bofill (2016-12-11). Planning clinical trials with CompARE. International Conference of the ERCIM Working Group on Computing & Statistics.](http://www.cmstatistics.org/RegistrationsV2/CMStatistics2016/viewSubmission.php?in=1251&token=p6p821n3qo8nr66380r3qo596q9s6ss2)

14. [G. Gómez, M. Gómez and M. Bofill(2016-09-05). Planning clinical trials involving composite endpoints. Congreso Nacional de Estadística e Investigación Operativa.](http://seio2016.com/es/trabajos/848/planning-clinical-trials-involving-composite-endpoints)

15. [M. Bofill and G. Gómez(2016-08-23). The efficient choice of a primary binary endpoint for sample size assessment. International Society for Clinical Biostatistics.](http://www.biometricsociety.net/wp-content/uploads/3_Mbofill-IIJseb.pdf)

